---
config:
  theme: dark
  look: classic
  layout: flowchart
---
flowchart LR

%% Nodes definition
    USER["{{USER}}"] 
    COMMENT["{{COMMENT_INPUT}}"]
    BLAZOR["{{BLAZOR_CLIENT}}"]
    API_COMMENT["{{API_COMMENT}}"]
    MEDIATOR["{{MEDIATOR_COMMAND}}"]
    COMMENT_SVC["{{SERVICE_COMMENT}}"]
    REPO_COMMENT["{{REPO_COMMENT}}"]
    DB["({{SQL_DB}})"]
    ADDED["{{COMMENT_ADDED}}"]

%% Flow definition
    USER --> COMMENT
    COMMENT --> BLAZOR
    BLAZOR -->|"POST /comments (JWT)"| API_COMMENT
    API_COMMENT --> MEDIATOR
    MEDIATOR --> COMMENT_SVC
    COMMENT_SVC --> REPO_COMMENT
    REPO_COMMENT --> DB
    DB --> ADDED
    ADDED --> BLAZOR
