---
config:
  theme: dark
  look: classic
  layout: flowchart
---
flowchart LR

%% Nodes definition
    USER["{{USER}}"]
    BLAZOR["{{BLAZOR_CLIENT}}"]
    API["{{API_TICKET}}"]
    MEDIATOR["{{MEDIATOR_QUERY}}"]
    SERVICE["{{SERVICE_TICKET}}"]
    REPO["{{REPO_TICKET}}"]
    DB["({{SQL_DB}})"]
    BLAZOR
    STATE["{{STATE_MANAGER}}"]

%% Flow definition
    USER --> |"{{OPEN_DASHBOARD}}"| BLAZOR
    BLAZOR --> |"GET /tickets (JWT)"| API
    API --> MEDIATOR
    MEDIATOR --> SERVICE
    SERVICE --> REPO
    REPO --> DB
    DB --> API
    API --> |"{{TICKETS_RETURNED}}"| BLAZOR
    BLAZOR --> STATE