---
config:
  theme: dark
  look: classic
  layout: flowchart
---
flowchart LR

%% Nodes definition
    EVENT["{{EVENT_SOURCE}}"] 
    NOTIF_SVC["{{NOTIF_SERVICE}}"]

    subgraph PERSISTANCE
        REPO_NOTIF["{{REPO_NOTIF}}"]
        SQL_DB["{{SQL_DB}}"]
    end

    subgraph PUSH_FLOW
        PUSH["{{PUSH_SIGNALR}}"]
        HUB["{{SIGNALR_HUB}}"]
        CLIENTS["{{CLIENT_CONNECTED}}"]
    end

%% Flow definition
    EVENT --> NOTIF_SVC
    NOTIF_SVC --> REPO_NOTIF
    REPO_NOTIF --> SQL_DB
    NOTIF_SVC --> PUSH
    PUSH --> HUB
    HUB --> CLIENTS