---
config:
  theme: dark
  look: classic
  layout: flowchart
---
flowchart LR
    EVENT["{{EVENT_SOURCE}}"] --> NOTIF_SVC["{{NOTIF_SERVICE}}"]

    subgraph PERSISTANCE
        NOTIF_SVC --> NOTIF_REPO["{{NOTIF_REPO}}"]
        NOTIF_REPO --> SQL_DB["{{SQL_DB}}"]
    end

    subgraph PUSH_FLOW
        NOTIF_SVC --> PUSH["{{PUSH_SIGNALR}}"]
        PUSH --> HUB["{{SIGNALR_HUB}}"]
        HUB --> CLIENTS["{{CLIENT_CONNECTED}}"]
    end
