---
config:
  theme: dark
  look: classic
  layout: flowchart
---
flowchart LR

%% Nodes definition
    USER["{{USER}}"] 
    FORM["{{FORM_TICKET}}"]
    BLAZOR_CLIENT["{{BLAZOR_CLIENT}}"]
    API_TICKET["{{API_TICKET}}"]
    MEDIATOR["{{MEDIATOR}}"]
    SERVICE_TICKET["{{SERVICE_TICKET}}"]
    REPO_TICKET["{{REPO_TICKET}}"]
    SQL_DB["{{SQL_DB}}"]
    CREATED["{{TICKET_CREATED}}"]

%% Flow definition
    USER --> FORM
    FORM --> BLAZOR_CLIENT
    BLAZOR_CLIENT --> API_TICKET
    API_TICKET --> MEDIATOR
    MEDIATOR --> SERVICE_TICKET
    SERVICE_TICKET --> REPO_TICKET
    REPO_TICKET --> SQL_DB
    SQL_DB --> CREATED
    CREATED --> BLAZOR_CLIENT