---
config:
  theme: dark
  look: classic
  layout: flowchart
---
flowchart LR

%% Nodes definition
    USER["{{USER}}"] 
    ACCESS["{{OPEN_DASHBOARD}}"]
    BLAZOR_CLIENT["{{BLAZOR_CLIENT}}"]
    API_TICKET["{{API_TICKET}}"]
    MEDIATOR["{{MEDIATOR_QUERY}}"]
    SERVICE_TICKET["{{SERVICE_TICKET}}"]
    REPO_TICKET["{{REPO_TICKET}}"]
    SQL_DB["{{SQL_DB}}"]
    RESULT["{{TICKETS_RETURNED}}"]
    BLAZOR_CLIENT

%% Flow definition
    USER --> ACCESS
    ACCESS --> BLAZOR_CLIENT
    BLAZOR_CLIENT --> API_TICKET
    API_TICKET --> MEDIATOR
    MEDIATOR --> SERVICE_TICKET
    SERVICE_TICKET --> REPO_TICKET
    REPO_TICKET --> SQL_DB
    SQL_DB --> RESULT
    RESULT --> BLAZOR_CLIENT