---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition 
A["{{ADMIN}}"]
B["{{ADMIN_OPEN_USER_PROFILE}}"]
C["{{CLICK_DELETE_USER}}"]
D["{{FORM_CHOOSE_REASON}}"]
E["{{CONFIRM_DELETE}}"]
F["{{IMMEDIATE_USER_DELETION}}"]
Gn["{{DISPLAY_ERROR}}"]
Gy["
    {{SEND_EMAIL_USER}}
    • {{ACCOUNT_DELETED}}
    • {{REASON_PROVIDED_ADMIN}}
"]
H["{{DISPLAY_SUCCESS_MESSAGE}}"]

%% Flow definition
A --> B
B --> C
C --> D
D --> E
E --> F
F --> |"{{ERROR}}"| Gn
F --> |"{{OK}}"| Gy
Gy --> H