---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{ADMIN}}"]
B["{{ADMIN_OPEN_ADMIN_INTERFACE}}"]
C["{{ADMIN_NAVIGATE_USER_MANAGEMENT}}"]
D["{{DISPLAY_USER_LIST}}"]
E["{{DISPLAY_USER_INFO}}"]
F["{{ADMIN_WANT_FILTER_SEARCH}}?"]
Gy["{{ADMIN_APPLY_FILTER_SEARCH}}"]
Gn["{{ADMIN_VIEW_USER}}"]

%% Flow definition
A --> B
B --> C
C --> D
D --> E
E --> F
F -- "{{YES}}" --> Gy
Gy --> D
F -- "{{NO}}" --> Gn