---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{ADMIN}}"]
B["{{ADMIN_OPEN_USER_PROFILE}}"]
C["{{ADMIN_CLICK_CHANGE_ROLE}}"]
D["{{ADMIN_SELECT_NEW_ROLE}}"]
E["{{CONFIRM_ROLE_CHANGE}}"]
Fn["{{ACTION_CANCELLED}}"]
Fy["{{UPDATE_ROLE}}"]
G["{{DISPLAY_SUCCESS_MESSAGE}}"]
H["{{SEND_NOTIFICATION_USER}}"]

%% Flow definition
A --> B
B --> C
C --> D
D --> E
E -->|"{{NO}}"| Fn
E -->|"{{YES}}"| Fy
Fy --> G
G --> H