---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{USER}}"]
B["{{USER_SELECT_POST}}"]
C["{{USER_CLICK_EDIT_COMMENT}}"]
D["{{USER_MODIFY_COMMENT_TEXT}}"]
E["{{USER_CLICK_UPDATE}}"]
Fy["{{SEND_UPDATE_REQUEST}}"]
Fn["{{DISPLAY_ERROR}}  {{INVALID_FIELDS}}"]
Gn["{{DISPLAY_ERROR}}"]
Gy["{{UPDATE_COMMENT}}"]
J["{{DISPLAY_SUCCESS_MESSAGE}}"]

%% Flow definition
A --> B
B --> C
C --> D
D --> E
E --> Fy
Fy -->|success| Gy
Gy --> J
Fy -->|error: invalid fields| Fn
Fy -->|error: other| Gn
Gn --> B
Fn --> D