---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{USER}}"]
B["{{OPEN_TICKET}}"]
C["{{ENTER_COMMENT}}"] 
D["{{VALIDATE}}"]
En["{{DISPLAY_ERROR}} {{EMPTY_FIELDS}}"]
Ey["{{ADD_COMMENT}}"]
F["{{DISPLAY_SUCCESS_MESSAGE}}"]

%% Flow definition
A --> B
B --> C
C --> D
D -->|"{{EMPTY_FIELDS}}"| En
En --> C
D -->|"{{OK}}"| Ey
Ey --> F