---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{USER}}"]
B["{{USER_SELECT_POST}}"]
C["{{USER_SELECT_COMMENT}}"]
D["{{CLICK_DELETE}}"]
Iy["{{DELETE_COMMENT}}"]
In["{{DISPLAY_ERROR}}"]
K["{{DISPLAY_SUCCESS_MESSAGE}}"]
L["{{UPDATE_COMMENT_LIST}}"]

%% Flow definition
A --> B
B --> C
C --> D
D -->|"{{CANNOT_DELETE_COMMENT}}"| In
In --> C
D -->|"{{OK}}"| Iy
Iy --> K
K --> L