---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD
A["{{USER_PERFORMS_ACTION}}"] --> B["{{SYSTEM_CHECK_LOG_REQUIRED}}"]
B -->|"{{YES}}"| C["{{BUILD_LOG_ENTRY}}"]
C --> D["{{SAVE_GLOBAL_LOG}}"]
D --> E["{{RETURN_SUCCESS}}"]
B -->|"{{NO}}"| F["{{NO_LOGGING}}"]