---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD
A["{{MODIFICATION_TICKET_COMMENT}}"] --> B["{{DETECT_ACTION_TYPE}}"]
B --> C["{{ASSOCIATE_ACTION_TICKET}}"]
C --> D["{{RECORD_ACTION_DETAILS}}"]
D --> E["{{UPDATE_TICKET_TIMELINE}}"]
E --> F["{{END}}"]