---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{USER_OR_ADMIN}}"] 
B["{{OPEN_TICKET}}"]
C["{{OPEN_ADD_ASSIGNEE_MENU}}"]
Dn["{{ACCESS_ERROR}}"]
Dy["{{SELECT_USER}}"]
F["{{ADD_ASSIGNED_USER}}"]
H["{{DISPLAY_SUCCESS_MESSAGE}}"]

%% Flow definition
A --> B
B --> C
C -->|"{{ERROR}}"| Dn
C -->|"{{OK}}"| Dy
Dy --> F
F --> H