---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{USER_OR_ADMIN}}"] 
B["{{OPEN_TICKET_LIST}}"]
C1["{{DISPLAY_USER_TICKETS}}"]
C2["{{DISPLAY_ALL_TICKETS}}"]

%% Flow definition
A --> B
B -->|"{{STANDARD_USER}}"| C1
B -->|"{{ADMIN}}"| C2