---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TB

%% Nodes definition
A["{{USER}}"] 
B["{{OPEN_TICKET}}"]
C["{{CLICK_EDIT}}"]
D["{{FILL_FIELDS}}"]
E["{{VALIDATE}}"]
Fn["{{DISPLAY_ERROR}} {{NOT_AUTHORIZED}}"]
Fn2["{{DISPLAY_ERROR}} {{INVALID_FIELDS}}"]
Fy["{{TICKET_UPDATED}}"]
G["{{DISPLAY_SUCCESS_MESSAGE}}"]

%% Flow definition
A --> B
B --> C
C --> D
D --> E
E -->|"{{NOT_AUTHORIZED}}"| Fn
Fn --> A
E -->|"{{INVALID_FIELDS}}"| Fn2
Fn2 --> D
E -->|"{{OK}}"| Fy
Fy --> G