---
config:
theme: dark
look: classic
layout: dagre
---
flowchart TD
A["{{USER_ADMIN}}"] --> B["{{OPEN_TICKET}}"]
B --> C["{{CLICK_DELETE}}"]
C -->|"{{NOT_AUTHORIZED}}"| D["{{ACCESS_ERROR_403}}"]
C -->|"{{AUTHORIZED}}"| E["{{API_DELETE_TICKET}}"]
E --> F["{{DELETE_COMMENTS_HISTORY}}"]
F --> G["{{CONFIRM_DELETION}}"]