---
config:
theme: dark
look: classic
layout: dagre
---
flowchart TD
A["{{USER_OR_ADMIN}}"] --> B["{{OPEN_TICKET}}"]
B --> C["{{OPEN_ADD_ASSIGNEE_MENU}}"]
C --> D["{{API_CHECK_PERMISSIONS}}"]
D -->|"{{NOT_AUTHORIZED}}"| E["{{ACCESS_ERROR}}"]
E --> B
D -->|"{{OK}}"| F["{{SELECT_USER}}"]
F --> G["{{API_ADD_ASSIGNED_USER}}"]
G --> H["{{UPDATE_VISIBILITY}}"]
H --> I["{{DISPLAY_UPDATED_TICKET}}"]