---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TB

%% Nodes definition
A["{{USER}}"]
B["{{OPEN_NEW_TICKET_PAGE}}"]
C["{{FILL_FIELDS}}"]
D["{{VALIDATE}}"]
En["{{DISPLAY_ERROR}} {{INVALID_FIELDS}}"]
Ey["{{TICKET_CREATED}}"]
F["{{DISPLAY_SUCCESS_MESSAGE}}"]

%% Flow definition
A --> B
B --> C
C --> D
D -->|"{{INVALID_FIELDS}}"| En
En --> C
D -->|"{{OK}}"| Ey
Ey --> F