---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TB
A["{{USER}}"] --> B["{{OPEN_TICKET}}"]
B --> C["{{MODIFY_DESC_STATUS_PRIORITY}}"]
C --> D["{{VALIDATE}}"]
D -- "{{NOT_AUTHORIZED}}" --> E@{ label: "{{ERROR_NO_ACCESS}}" }
E --> B
D -- "{{INVALID_FIELDS}}" --> F["{{DISPLAY_ERRORS}}"]
F --> C
D -- "{{VALID}}" --> G["{{API_UPDATE_TICKET}}"]
G --> H@{ label: "{{API_ADD_HISTORY_ENTRY}}" }
H --> I["{{DISPLAY_UPDATED_TICKET}}"]
E@{ shape: rect}
H@{ shape: rect}