---
config:
  look: classic
  theme: dark
  layout: dagre
---
flowchart TD

%% Nodes definition
A["{{USER_OR_ADMIN}}"] 
B["{{OPEN_TICKET}}"]
C["{{CLICK_DELETE}}"]
Dn["{{DISPLAY_ERROR}} {{NOT_AUTHORIZED}}"]
Dy["{{TICKET_DELETED}}"]
E["{{DISPLAY_SUCCESS_MESSAGE}}"]

%% Flow definition
A --> B
B --> C
C -->|"{{NOT_AUTHORIZED}}"| Dn
C -->|"{{AUTHORIZED}}"| Dy
Dy --> E