---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{USER}}"]
B["{{OPEN_ACCOUNT_SETTINGS}}"]
C["{{USER_CLICK_CHANGE_EMAIL}}"]
D["{{USER_FILL_FIELDS}}"]
E["{{USER_CLICK_SAVE}}"]
Fy["{{EMAIL_UPDATED}}"]
Fn["{{DISPLAY_ERROR}} {{INVALID_FIELDS}}"]
Gn["{{DISPLAY_ERROR}} {{EMAIL_ALREADY_USED}}"]
Gy["{{DISPLAY_SUCCESS_MESSAGE}}"]

%% Flow definition
A--> B
B --> C
C --> D
D --> E
E -->|"{{INVALID_FIELDS}}"| Fn
Fn --> D
E -->|"{{EMAIL_ALREADY_USED}}"| Gn
Gn --> D
E -->|"{{OK}}"| Fy
Fy --> Gy