---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{VISITOR}}"]
B["{{OPEN_LOGIN_PAGE}}"]
C["{{FILL_FIELDS}}"]
D["{{USER_CLICK_LOGIN}}"]
E["{{DISPLAY_ERROR}} {{INVALID_FIELDS}}"]
G["{{DISPLAY_ERROR}} {{INVALID_CREDENTIALS}}"]
I["{{LOGIN_SUCCESS}}"]
J["{{REDIRECT_DASHBOARD}}"]

%% Flow definition
A --> B
B --> C
C --> D
D -->|"{{INVALID_FIELDS}}"| E
E --> C
D -->|"{{INVALID_CREDENTIALS}}"| G
G --> C
D -->|"{{OK}}"| I
I --> J