---
config:
theme: dark
look: classic
layout: dagre
---
flowchart TD
U["{{VISITOR_USER}}"] --> A["{{PAGE_FORGOT_PASSWORD}}"]
A --> B["{{USER_ENTER_EMAIL}}"]
B --> C["{{BACKEND_CHECK_EMAIL_EXISTS}}"]
C -->|"{{EXISTS}}"| D["{{SEND_RESET_PASSWORD_EMAIL}}"]
C -->|"{{NOT_EXISTS}}"| X["{{DISPLAY_NO_ACCOUNT_FOUND}}"]
D --> E["{{USER_CLICK_EMAIL_LINK}}"]
E --> F["{{BACKEND_VERIFY_TOKEN}}"]
F -->|"{{VALID}}"| G["{{PAGE_ENTER_NEW_PASSWORD}}"]
F -->|"{{INVALID_FIELDS}}"| Y["{{ERROR_LINK_EXPIRED}}"]
G --> H["{{USER_VALIDATE_NEW_PASSWORD}}"]
H --> I["{{UPDATE_PASSWORD_DB}}"]
I --> J["{{LOG_PASSWORD_RESET_ACTION}}"]
J --> K["{{REDIRECT_LOGIN_SUCCESS_MESSAGE}}"]