---
config:
theme: dark
look: classic
layout: dagre
---
flowchart TB
A["{{USER}}"] --> B@{ label: "{{OPEN_REGISTRATION_PAGE}}" }
B --> C["{{ENTER_EMAIL_USERNAME_PASSWORD}}"]
C --> D["{{VALIDATE_REGISTRATION_FORM}}"]
D -- "{{INVALID_FIELDS}}" --> E["{{DISPLAY_VALIDATION_ERRORS}}"]
E --> C
D -- "{{VALID_FIELDS}}" --> F@{ label: "{{API_CHECK_EMAIL_EXISTS}}" }
F -- "{{EMAIL_ALREADY_USED}}" --> G["{{DISPLAY_EMAIL_REGISTERED}}"]
G --> C
F -- "{{EMAIL_AVAILABLE}}" --> H@{ label: "{{API_CREATE_USER}}" }
H --> I["{{API_SEND_CONFIRMATION_EMAIL}}"]
I --> J["{{DISPLAY_ACCOUNT_CREATED}}"]
B@{ shape: rect}
F@{ shape: rect}
H@{ shape: rect}