---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{USER}}"] 
B["{{OPEN_ACCOUNT_SETTINGS}}"]
C["{{CLICK_DELETE_ACCOUNT}}"]
D["{{DISPLAY_CONFIRMATION_EMAIL_SENT}}"]
E["{{USER_CLICK_EMAIL_LINK}}"]
Fn["{{DISPLAY_ERROR}} {{LINK_EXPIRED_INVALID}}"]
Fy["{{ACCOUNT_DELETED}}"]
G["{{DISPLAY_SUCCESS_MESSAGE}}"]

%% Flow definition
A --> B
B --> C
C --> D
D --> E
E -->|"{{LINK_EXPIRED_INVALID}}"| Fn
E -->|"{{LINK_VALID}}"| Fy
Fy --> G
