---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TB

%% Nodes definition
A["{{VISITOR}}"]
B["{{OPEN_REGISTRATION_PAGE}}"]
C["{{VISITOR}} {{FILL_FIELDS}}"]
D["{{CLICK_SUBMIT}}"]
En["{{DISPLAY_ERROR}} {{INVALID_FIELDS}}"]
En2["{{DISPLAY_ERROR}} {{EMAIL_ALREADY_USED}}"]
Ey["{{CREATE_ACCOUNT}}"]
F["{{DISPLAY_SUCCESS_MESSAGE}}"]
G["{{REDIRECT_LOGIN_PAGE}}"]

%% Flow definition
A --> B
B --> C
C --> D
D -->|"{{INVALID_FIELDS}}"| En
En --> C
D -->|"{{EMAIL_ALREADY_USED}}"| En2
En2 --> C
D -->|"{{OK}}"| Ey
Ey --> F
F --> G
