---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD
A["{{USER_OPEN_ACCOUNT_SETTINGS}}"] --> B["{{USER_CLICK_CHANGE_PASSWORD}}"]
B --> C["{{FORM_OLD_NEW_CONFIRM_PASSWORD}}"]
C --> D["{{USER_FILL_FIELDS}}"]
D --> E["{{USER_CLICK_SAVE}}"]
E --> F["{{FRONTEND_VALIDATE_PASSWORD}}"]
F -->|"{{VALIDATED}}"| G["{{SEND_PASSWORD_UPDATE_REQUEST}}"]
F -->|"{{ERROR}}"| F1["{{DISPLAY_ERROR}}"]
G --> H["{{BACKEND_VERIFY_PASSWORD}}"]
H -->|"{{OK}}"| I["{{HASH_UPDATE_PASSWORD_DB}}"]
H -->|"{{ERROR}}"| H1["{{ERROR_401_403_WRONG_PASSWORD}}"]
I --> J["{{RETURN_SUCCESS_TO_FRONTEND}}"]
J --> K["{{DISPLAY_PASSWORD_UPDATED}}"]