---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{VISITOR}}"] 
B["{{PAGE_FORGOT_PASSWORD}}"]
C["{{USER_ENTER_EMAIL}}"]
Dn["{{DISPLAY_NO_ACCOUNT_FOUND}}"]
Dy["{{SEND_RESET_PASSWORD_EMAIL}}"]
F["{{USER_CLICK_EMAIL_LINK}}"]
Gy["{{PAGE_ENTER_NEW_PASSWORD}}"]
Gn["{{DISPLAY_ERROR}} {{LINK_EXPIRED_INVALID}}"]
H["{{USER_VALIDATE_NEW_PASSWORD}}"]
I["{{PASSWORD_UPDATED}}"]
J["{{DISPLAY_SUCCESS_MESSAGE}}"]
K["{{REDIRECT_LOGIN_PAGE}}"]

%% Flow definition
A --> B
B --> C
C --> Dy
Dy -->|success| F
Dy -->|error: no account found| Dn
Dn --> C
F --> Gy
Gy --> H
H --> I
I --> J
J --> K
Dy -->|error: link expired/invalid| Gn
Gn --> B
