---
config:
    theme: dark
    look: classic
    layout: dagre
---
flowchart TD

%% Nodes definition
A["{{USER}}"] 
B["{{OPEN_ACCOUNT_SETTINGS}}"]
C["{{USER_CLICK_CHANGE_PASSWORD}}"]
D["{{USER_FILL_FIELDS}}"]
E["{{USER_CLICK_SAVE}}"]
Gy["{{PASSWORD_UPDATED}}"]
Gn["{{DISPLAY_ERROR}} {{INVALID_FIELDS}}"]
Hy["{{DISPLAY_SUCCESS_MESSAGE}}"]
Hn["{{DISPLAY_ERROR}} {{CURRENT_PASSWORD_INCORRECT}}"]

%% Flow definition
A --> B
B --> C
C --> D
D --> E
E -->|"{{INVALID_FIELDS}}"| Gn
Gn --> D
E -->|"{{CURRENT_PASSWORD_INCORRECT}}"| Hn
Hn --> D
E -->|"{{OK}}"| Gy
Gy --> Hy
