flowchart TB

    subgraph COMMENTS["{{COMMENTS_TABLE}}"]
        direction LR

        C1["**{{FIELD_CONTENT}}**<br/>{{TYPE_TEXT}} (1000)"]
        C2["**{{FIELD_TICKET}}**<br/>{{TYPE_INTEGER}}"]
        C3["**{{FIELD_USER}}**<br/>{{TYPE_INTEGER}}"]
        C4["**{{FIELD_CREATED_ON}}**<br/>{{TYPE_DATE}}"]
        C5["**{{FIELD_UPDATED_ON}}**<br/>{{TYPE_DATE}}"]
    end
