---
config:
  theme: redux-dark
  look: classic
  layout: dagre
---
flowchart TD
    A[Admin ouvre l'interface d'administration] --> B[Admin navigue vers 'Gestion des utilisateurs']
    B --> C[Le système récupère la liste des utilisateurs]
    C --> D[Le système affiche : email, pseudo, rôle, statut]
    D --> E{Admin souhaite filtrer/rechercher ?}
    E -- Oui --> F[Admin applique un filtre ou une recherche]
    F --> C
    E -- Non --> G[Admin consulte un utilisateur]
    G --> H[Fin]
