---
config:
  theme: redux-dark
  look: classic
  layout: dagre
---
flowchart TD

    A[Administrateur] --> B[Accéder à la fiche utilisateur]
    B --> C[Cliquer : Supprimer l’utilisateur]

    C --> D[Formulaire : Saisir la raison<br/>de la suppression]
    D --> E[Validation de l’action]

    E --> F[Suppression immédiate de l’utilisateur]
    F --> G[Journalisation de l'action]

    G --> H[Envoi automatique d’un e-mail à l’utilisateur<br/>• Compte supprimé<br/>• Raison fournie par l’admin]
