---
config:
  theme: redux-dark
  look: classic
  layout: dagre
---
flowchart TD

A[Admin ouvre l’interface de modération] --> B[Admin sélectionne un commentaire]
B --> C[Admin clique sur 'Supprimer']
C --> D[Formulaire : choisir/écrire la raison]
D --> E[Admin confirme]

E --> F[Envoi requête Suppression avec raison]

F --> G["Backend vérifie :  
- Authentification admin  
- Champs optionnels (raison suppression)"]

G -->|OK| H[Suppression en base]
G -->|Erreur| G1[Retour erreur : 401, 403]

H --> I[Envoi email à l’utilisateur avec la raison]
I --> J[Retour succès au frontend admin]
J --> K[Mise à jour de la liste des commentaires]

