---
config:
  theme: redux-dark
  look: classic
  layout: dagre
---
flowchart TD

    A[Utilisateur] --> B[Ouvre un ticket]
    B --> C[Saisit commentaire]
    C --> D[Valider]

    D -->|Champs vides| E[Erreur]
    E --> C

    D -->|OK| F[API : Ajouter commentaire]
    F --> G[Enregistrer action historique]
    G --> H[Afficher commentaire ajouté]