---
config:
  theme: redux-dark
  look: classic
  layout: dagre
---
flowchart TD
    A[Admin effectue une action critique] --> B[Le système marque l'action comme 'sensible']
    B --> C[Création d'une entrée de log avec métadonnées renforcées]
    C --> D[Enregistrement dans l'historique global]
    D --> E[Optionnel : Notification Audit interne]
    E --> F[Fin]
