---
config:
  theme: redux-dark
  look: classic
  layout: dagre
---
flowchart TD
    A[Modification sur Ticket ou Commentaire] --> B[Détecter type d'action : Création, Modification, Suppression]
    B --> C[Associer l'action au Ticket concerné]
    C --> D[Enregistrer : utilisateur, action, ancienne valeur, nouvelle valeur, date]
    D --> E[Mettre à jour la timeline du ticket]
    E --> F[Fin]
