---
config:
  theme: redux-dark
  look: classic
  layout: dagre
---
flowchart TB
    A["Utilisateur"] --> B["Ouvre un ticket"]
    B --> C["Modifie description, état ou priorité"]
    C --> D["Valider"]
    D -- Non autorisé --> E@{ label: "Erreur : pas d'accès" }
    E --> B
    D -- Champs invalides --> F["Afficher erreurs"]
    F --> C
    D -- Valide --> G["API : Mettre à jour le ticket"]
    G --> H@{ label: "API : Ajouter entrée dans l'historique" }
    H --> I["Afficher ticket mis à jour"]

    E@{ shape: rect}
    H@{ shape: rect}