---
config:
  theme: redux-dark
  look: classic
  layout: dagre
---
flowchart TD

A[Utilisateur ouvre Paramètres du compte] --> B[Utilisateur clique sur Modifier Mot de passe]
B --> C[Formulaire avec : ancien mdp, nouveau mdp, confirmation]
C --> D[Utilisateur remplit les champs]
D --> E[Utilisateur clique sur Enregistrer]

E --> F["Frontend valide :  
- champs remplis  
- nouveau mdp conforme (complexité)  
- confirmation = nouveau mdp"]

F -->|Validé| G[Envoi requête mise à jour mot de passe]
F -->|Erreur| F1[Affichage erreur]

G --> H[Backend vérifie :  
- Authentification  
- Ancien mdp correct  
- Nouveau mdp conforme]

H -->|OK| I[Hash + mise à jour du mot de passe en base]
H -->|Erreur| H1[401, 403 ou ancien mdp incorrect]

I --> J[Retour succès au frontend]
J --> K[Affichage message : “Mot de passe mis à jour”]
