---
config:
  theme: redux-dark
  look: classic
  layout: dagre
---
flowchart TB
    A["Utilisateur"] --> B@{ label: "Ouvre la page d'inscription" }
    B --> C["Saisit email + pseudo + mot de passe"]
    C --> D["Valider le formulaire"]
    D -- Champs invalides --> E["Afficher erreurs de validation"]
    E --> C
    D -- Champs valides --> F@{ label: "API : Vérifier si l'email existe" }
    F -- Email déjà utilisé --> G["Afficher message : email déjà enregistré"]
    G --> C
    F -- Email libre --> H@{ label: "API : Créer l'utilisateur" }
    H --> I["API : Envoyer email de confirmation"]
    I --> J["Afficher message : compte créé avec succès"]

    B@{ shape: rect}
    F@{ shape: rect}
    H@{ shape: rect}