---
config:
  theme: redux-dark
  look: classic
  layout: dagre
---
flowchart TD

    A[Utilisateur] --> B[Ouvre page de connexion]
    B --> C[Entre email + mot de passe]
    C --> D[Valide le formulaire]

    D -->|Champs invalides| E[Afficher erreurs]
    E --> C

    D -->|Champs valides| F[API : Vérifier utilisateur]

    F -->|Identifiants incorrects| G[Erreur : identifiants invalides]
    G --> C

    F -->|OK| H[API : Générer Token JWT]
    H --> I[Connexion réussie]
    I --> J[Redirection tableau de bord]