---
config:
    theme: dark
    look: classic
    layout: dagre
---
graph TD

%% Nodes definition
A["{{LAYER_PRESENTATION}}: Blazor"] 
B["{{LAYER_APPLICATION}}: .NET"]
C["{{LAYER_DOMAIN}}: DDD"]
D["{{LAYER_INFRASTRUCTURE}}: EF Core + SQL"]
E["({{DATABASE}})"]
F["{{SECURITY}}: JWT/Identity"]

%% Flow definition
A --> B
B --> C
C --> D
D --> E
B --> F
F --> B