---
config:
  layout: elk
---
flowchart LR
subgraph date["22:03 24/11/2025"]
  %% Bloc Define 
 subgraph VIS["Visiteur"]
        Visitor(["Visiteur"])
        Login("Se connecter")
        Register("Créer un compte")
        ForgotPW("Réinitialiser le\nmot de passe")
  end
 subgraph USR["Utilisateur"]
        User(["Utilisateur"])
        Logout("Se déconnecter")
        DelAccount("Supprimer le compte")
        EditProfile("Modifier le profil")
        Tickets("Gérer ses tickets")
        Comments("Gérer ses commentaires")
        Pseudo("Modifier pseudo")
        Email("Modifier e-mail")
        Password("Modifier mot de passe")
        CreateTicket("Créer un ticket")
        ListTicket("Lister ses tickets")
        ViewTicket("Consulter un ticket")
        EditTicket("Modifier un ticket")
        AssignTicket("Attribuer un ticket")
        DeleteTicket("Supprimer un ticket")
        CreateComment("Créer un commentaire")
        EditComment("Modifier un commentaire")
        DeleteComment("Supprimer un commentaire")
  end
 subgraph ADM["Administrateur"]
        Admin(["Administrateur"])
        MngUsers("Gérer les utilisateurs")
        Moderation("Modération des contenus")
        DeleteUser("Supprimer un utilisateur")
        ChangeRole("Changer le rôle")
        DeleteTicketMod("Supprimer ticket utilisateur")
        DeleteCommentMod("Supprimer commentaire utilisateur")
  end
  %% Relation declaration
    Visitor --> Login & Register & ForgotPW
    User --> Logout & DelAccount & EditProfile & Tickets & Comments
    EditProfile --- Pseudo & Email & Password
    Tickets --- CreateTicket & ListTicket & ViewTicket & EditTicket & AssignTicket & DeleteTicket
    Comments --- CreateComment & EditComment & DeleteComment
    Admin --> MngUsers & Moderation
    MngUsers --- DeleteUser & ChangeRole
    Moderation --- DeleteTicketMod & DeleteCommentMod
    Register -.-> Journal("Journaliser les actions")
    ForgotPW -.-> Journal
    Logout -.-> Journal
    DelAccount -.-> Journal
    Pseudo -.-> Journal
    Email -.-> Journal
    Password -.-> Journal
    CreateTicket -.-> Journal
    EditTicket -.-> Journal
    AssignTicket -.-> Journal
    DeleteTicket -.-> Journal
    CreateComment -.-> Journal
    EditComment -.-> Journal
    DeleteComment -.-> Journal
    DeleteUser -.-> Journal
    ChangeRole -.-> Journal
    DeleteTicketMod -.-> Journal
    DeleteCommentMod -.-> Journal

    style VIS fill:#FFF2CC,stroke:#d6b656,stroke-width:2px
    style USR fill:#DAE8FC,stroke:#6c8ebf,stroke-width:2px
    style ADM fill:#E1D5E7,stroke:#9673a6,stroke-width:2px
end